### ISSUE TITLE
Panic on nested list

### ISSUE THREAD

**Issue by patataofcourse** [patataofcourse/AdventureScript#2]
Probably a fault of simplifying in brackets mode, gotta check that bracket detecting method.

Backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/parsing.rs:341:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: adventure_script::parsing::evaluate
             at ./src/parsing.rs:339:25
   5: adventure_script::parsing::parse_text
             at ./src/parsing.rs:57:25
   6: adventure_script::parsing::parse_line
             at ./src/parsing.rs:23:26
   7: adventure_script::AdventureScriptGame::run
             at ./src/lib.rs:42:19
   8: adventure_script::main
             at ./src/main.rs:5:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  ```

**Comment by patataofcourse** [comment]
Fixed in 8fc8907edd64b5c786f64517e5ccd36b0b57f4f5
